//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracerX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TracerX.ViewedPath[] RecentFiles {
            get {
                return ((TracerX.ViewedPath[])(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] ColWidths {
            get {
                return ((int[])(this["ColWidths"]));
            }
            set {
                this["ColWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] ColIndices {
            get {
                return ((int[])(this["ColIndices"]));
            }
            set {
                this["ColIndices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool[] ColSelections {
            get {
                return ((bool[])(this["ColSelections"]));
            }
            set {
                this["ColSelections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenDir {
            get {
                return ((string)(this["OpenDir"]));
            }
            set {
                this["OpenDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DuplicateTimes {
            get {
                return ((bool)(this["DuplicateTimes"]));
            }
            set {
                this["DuplicateTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RelativeTime {
            get {
                return ((bool)(this["RelativeTime"]));
            }
            set {
                this["RelativeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LineNumSeparator {
            get {
                return ((bool)(this["LineNumSeparator"]));
            }
            set {
                this["LineNumSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpandNewlines {
            get {
                return ((bool)(this["ExpandNewlines"]));
            }
            set {
                this["ExpandNewlines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public char IndentChar {
            get {
                return ((char)(this["IndentChar"]));
            }
            set {
                this["IndentChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int IndentAmount {
            get {
                return ((int)(this["IndentAmount"]));
            }
            set {
                this["IndentAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FindStrings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FindStrings"]));
            }
            set {
                this["FindStrings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepFilter {
            get {
                return ((bool)(this["KeepFilter"]));
            }
            set {
                this["KeepFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VersionCheckInterval {
            get {
                return ((int)(this["VersionCheckInterval"]));
            }
            set {
                this["VersionCheckInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2007-12-15")]
        public global::System.DateTime VersionLastChecked {
            get {
                return ((global::System.DateTime)(this["VersionLastChecked"]));
            }
            set {
                this["VersionLastChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TracerX.ColoringRule[] ColoringRules {
            get {
                return ((TracerX.ColoringRule[])(this["ColoringRules"]));
            }
            set {
                this["ColoringRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColoringEnabled {
            get {
                return ((bool)(this["ColoringEnabled"]));
            }
            set {
                this["ColoringEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportHeader {
            get {
                return ((bool)(this["ExportHeader"]));
            }
            set {
                this["ExportHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportIndentation {
            get {
                return ((bool)(this["ExportIndentation"]));
            }
            set {
                this["ExportIndentation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportFile {
            get {
                return ((string)(this["ExportFile"]));
            }
            set {
                this["ExportFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportSeparators {
            get {
                return ((bool)(this["ExportSeparators"]));
            }
            set {
                this["ExportSeparators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportDupTimes {
            get {
                return ((bool)(this["ExportDupTimes"]));
            }
            set {
                this["ExportDupTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportTimeAsText {
            get {
                return ((bool)(this["ExportTimeAsText"]));
            }
            set {
                this["ExportTimeAsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportTimeWithBlank {
            get {
                return ((bool)(this["ExportTimeWithBlank"]));
            }
            set {
                this["ExportTimeWithBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VersionCheckingAllowed {
            get {
                return ((bool)(this["VersionCheckingAllowed"]));
            }
            set {
                this["VersionCheckingAllowed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCalledMethods {
            get {
                return ((bool)(this["ShowCalledMethods"]));
            }
            set {
                this["ShowCalledMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdate {
            get {
                return ((bool)(this["AutoUpdate"]));
            }
            set {
                this["AutoUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TracerX.ViewedPath[] RecentFolders {
            get {
                return ((TracerX.ViewedPath[])(this["RecentFolders"]));
            }
            set {
                this["RecentFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchThreadsByName {
            get {
                return ((bool)(this["SearchThreadsByName"]));
            }
            set {
                this["SearchThreadsByName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bold {
            get {
                return ((bool)(this["Bold"]));
            }
            set {
                this["Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MM/dd/yy HH:mm:ss.fff")]
        public string CustomTimeFormat {
            get {
                return ((string)(this["CustomTimeFormat"]));
            }
            set {
                this["CustomTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomTimeFormat {
            get {
                return ((bool)(this["UseCustomTimeFormat"]));
            }
            set {
                this["UseCustomTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TimeUnits {
            get {
                return ((int)(this["TimeUnits"]));
            }
            set {
                this["TimeUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int MaxNetworkKB {
            get {
                return ((int)(this["MaxNetworkKB"]));
            }
            set {
                this["MaxNetworkKB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MaxRecords {
            get {
                return ((int)(this["MaxRecords"]));
            }
            set {
                this["MaxRecords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoReload {
            get {
                return ((bool)(this["AutoReload"]));
            }
            set {
                this["AutoReload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom")]
        public string RowColorDriver {
            get {
                return ((string)(this["RowColorDriver"]));
            }
            set {
                this["RowColorDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColoredLevels {
            get {
                return ((int)(this["ColoredLevels"]));
            }
            set {
                this["ColoredLevels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TracerX.SavedServer[] SavedRemoteServers {
            get {
                return ((TracerX.SavedServer[])(this["SavedRemoteServers"]));
            }
            set {
                this["SavedRemoteServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowServers {
            get {
                return ((bool)(this["ShowServers"]));
            }
            set {
                this["ShowServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] FilesColumns {
            get {
                return ((int[])(this["FilesColumns"]));
            }
            set {
                this["FilesColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] FoldersColumns {
            get {
                return ((int[])(this["FoldersColumns"]));
            }
            set {
                this["FoldersColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowViewedArchives {
            get {
                return ((bool)(this["ShowViewedArchives"]));
            }
            set {
                this["ShowViewedArchives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FileSortCol {
            get {
                return ((int)(this["FileSortCol"]));
            }
            set {
                this["FileSortCol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FolderSortCol {
            get {
                return ((int)(this["FolderSortCol"]));
            }
            set {
                this["FolderSortCol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFileTimesAgo {
            get {
                return ((bool)(this["ShowFileTimesAgo"]));
            }
            set {
                this["ShowFileTimesAgo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFolderTimesAgo {
            get {
                return ((bool)(this["ShowFolderTimesAgo"]));
            }
            set {
                this["ShowFolderTimesAgo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseFastScrollingKluge {
            get {
                return ((bool)(this["UseFastScrollingKluge"]));
            }
            set {
                this["UseFastScrollingKluge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLoggerTree {
            get {
                return ((bool)(this["ShowLoggerTree"]));
            }
            set {
                this["ShowLoggerTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowMethodTree {
            get {
                return ((bool)(this["ShowMethodTree"]));
            }
            set {
                this["ShowMethodTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DaysToSaveViewTimes {
            get {
                return ((int)(this["DaysToSaveViewTimes"]));
            }
            set {
                this["DaysToSaveViewTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTracerxFiles {
            get {
                return ((bool)(this["ShowTracerxFiles"]));
            }
            set {
                this["ShowTracerxFiles"] = value;
            }
        }
    }
}
